# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fbpages',
            name='page_at',
        ),
        migrations.AddField(
            model_name='fbpages',
            name='category',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
