# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20171103_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbpages',
            name='access_token',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
